### ISSUE TITLE
Lacking documentation for MS Teams notification

### ISSUE THREAD

**Issue by thiagolocatelli** [codefresh-io/steps#160]
Could you please post the YML step example used to produce the notification that is ilustrated in the README.md file as an image?

**Comment by dustinvanbuskirk** [comment]
The YAML of the step is posted.  The example image if from all of the defaults which are configured to pull in CF_ variables and pass them to the appropriate areas.

https://github.com/codefresh-io/steps/blob/master/incubating/msteams-notifier/example.yml#L3-L6

Then, there is the default mapping in the python script which fills out the remainder of the notifications.  The example in the README.md for success and failure is really the only thing that needs to be set outside of the webhook URL.

https://github.com/codefresh-io/steps/blob/master/incubating/msteams-notifier/script/pymsteams-notifier.py#L7-L28
