### ISSUE TITLE
Incorrect naming/or calling of argument for github-release

### ISSUE THREAD

**Issue by jonathanheaden** [codefresh-io/steps#257]
When using the base url argument, the passed parameter is being ignored because the field in index.js is called `baseurl` not `base-url` 

In run.sh it gets called using the string `base-url` 
https://github.com/codefresh-io/steps/blob/master/incubating/github-release/run.sh#L94

In index.js it is accepted as a parameter using the string `baseurl`
https://github.com/codefresh-io/steps/blob/master/incubating/github-release/github-release-cli/src/index.js#L18

**Comment by alex-codefresh** [comment]
@jonathanheaden @benjamin-lunt 
Thank you for catching this. The PR is merged
