### ISSUE TITLE
Serverless step name mismatch

### ISSUE THREAD

**Issue by dustinvanbuskirk** [codefresh-io/steps#42]
Serverless step is documented as `type: serverless` but expecting `type: lambda`

**Comment by sahil-9** [comment]
created a PR for the same
link https://github.com/codefresh-io/steps/pull/86

**Comment by kostis-codefresh** [comment]
@dustinvanbuskirk this was fixed by c13416ca5a00b0bd6aeea37eba8b4195914f7663
